[MongoDB]
    URL = "mongodb://localhost:27017/hschain"
    DBName = "hschain"
    PoolLimit = 1500
    Timeout = 60
    Mechanism = "DEFAULT"
    Username = "hschain"
    Password = "hschain"
[RPC]
    URL = "http://103.150.214.70:26657"
[LCD]
    URL = "http://103.150.214.70:1317"
[Public]
    Bech32PrefixAccAddr =  "hsc"
    Bech32PrefixValAddr =  "hscvaloper"
    ChainId =              "testnet"
    ChainName =            "hst"
    CoinGeckoId =         "hst"
    Denom = "hst"
    CoinToVoitingPower =   1.0
    ValidatorSetLimit =   100
    CoinPriceURL = "https://hsc.tt-cool.com/h5/hst_pri"
    GenesisAddress = "http://103.150.214.70:26657/genesis?"
[LOG]
    Level = "trace"
[Web]
    Addr = ":8080"